### PR TITLE
Spike: Multistage container builds

### PR DESCRIPTION
**Pull request by ian-noaa**
Use https://github.com/disney/meteor-base to build the MATS apps in a container. This is one path to building MATS with GitHub Actions.

You'll want to use the `build.sh` script as an example for how to build a container. And a `docker-compose.yml` file like the below to stand the app up.

```yml
version: "3.9"
services:
  aircraft:
    image: mats-meteor-base:aircraft
    ports:
      - "3001:80"
    links:
      - mongo
    volumes:
      - <path_to>/mats-settings/.../settings/aircraft/settings.json:/usr/app/settings/aircraft/settings.json:ro
  mongo:
    image: mongo
```

### CODE REVIEW

**Comment by ian-noaa** [comment]
@mollybsmith-noaa & @randytpierce - this builds off of the work I was doing in #638 to address running as root - I had to figure out how to build the container locally so figured while I was doing that I should take a look at multistage container builds. This change builds the MATS app in a container ([Disney's `meteor-base` image](https://github.com/disney/meteor-base)) and then copies the output to a new production container. The approach largely follows the example in [meteor-base](https://github.com/disney/meteor-base/blob/main/example/default.dockerfile) This has a few advantages:

- You can now build a production-equivalent MATS app locally (or on GitHub Actions) without installing any dev dependencies
- This gives us a "clean room" environment to make sure we don't miss a build or runtime dependency
- It's easy to set run in parallel on GitHub Actions

Since I had the multistage container working I then figured I'd go ahead and see if I can hook up GitHub Actions and that seems to be working quite well.

As I've been working on this some questions have come up that I want your input on.

## Dockerfile

Relevant code change: https://github.com/NOAA-GSL/MATS/pull/642/commits/e9e0b21009c52f022914fe08bdd9ae078922ed5a

* Do we like this one-Dockerfile-to-rule-them-all approach or would it be better to have individual Dockerfiles for each app? I went with one Dockerfile since that's the way we're currently doing it and it seems like our runtime dependencies are the same for all apps.
     * I do think we should have an individual Dockerfile for the `home` app since the runtime dependencies are different.
* Should we use the `entrypoint.sh` script provided by `meteor-base` instead of our [`run_app.sh`](https://github.com/NOAA-GSL/MATS/blob/spike-meteor-base/container-scripts/run_app.sh) script? It looks like `run_app.sh` does some things related to our settings file that [`entrypoint.sh`](https://github.com/disney/meteor-base/blob/main/src/docker/entrypoint.sh) doesn't. However, if we were able to remove `run_app.sh` it'd be one less script to maintain.

## GitHub Actions

Relevant code change: [e9e0b21..f42ea87](https://github.com/NOAA-GSL/MATS/pull/642/files/e9e0b21009c52f022914fe08bdd9ae078922ed5a..f42ea8755a675fca2ac45fa00927aae9e90c3e19)

* How do we feel about Docker Hub v GitHub Container Registry? (GHCR)
    * GHCR isn't perfect. However, it is something GSL's willing to support.
* We could integrate other linters, security scanners (e.g. - Trivy container scanning), and test suites in our CI pipeline - is there anything that would be nice to have run for our PR's to give us confidence the code is working the way we want it to?
* I believe it will be easiest to work with GitHub actions if we use git tags to control our version information so we don't need to talk to the app production status database. Using git tags also makes it very easy to kick off a production release. We can have this discussion in issue #625. 
* What do we currently need to do for production releases? Are they any different from a CI build of `development`?
    * Do we need nightly builds if we're rebuilding containers for each feature branch & each new merge to `development` and `main`?
* My inclination would be to build METexpress in its own repo since it's easy to automate the build to kick off when we push changes, it would charge for GitHub actions under dtcenter's org, and users would expect to find METexpress build artifacts in the METexpress project. What do you think?

## Process

* Where would we want to go next? What questions do you have? Is this a good format for these questions?

**Comment by mollybsmith-noaa** [comment]
Ah, understood. Sounds good, then!

**Comment by mollybsmith-noaa** [comment]
Sounds good. What I'm most concerned about with automating the production builds is that we _do not_ want one to happen every time someone pushes to that branch. A release might involve two or three pushes to main as documentation, etc, is sorted out, and the DTC folks push to main whenever they decide to update their girhub templates. If we let automated builds occur at these instances, we'll end up several version numbers ahead of where we want to be. Production builds should be extremely intentional, only when we're ready.

**Comment by ian-noaa** [comment]
Gotcha. Thanks for explaining a bit more! I agree that we want to be intentional about production builds and I think the way I've implemented the triggering for those builds will achieve that.

We will do automated development builds of main whenever it's pushed to. However, a production build can only be kicked off by someone running e.g. - `git tag v4.2.1 && git push origin v4.2.1`. (Or creating the tag matching that pattern from GitHub's UI)  And an integration build can only be kicked off by someone running e.g. - `git tag v4.2.1-rc1 && git push origin v4.2.1-rc1`. ("rc" stands for "release candidate") 

So the release process for a hypothetical 4.3.0 version would look like the following:
* Merge development to main (CI builds, tests & pushes to the development container registry)
* Tag an integration build off the main branch: `git switch main && git pull && git tag v4.3.0-rc1 && git push origin v4.3.0-rc1` (CI builds, tests & pushes to the development container registry with a v4.3.0-rc1 image tag)
* Provided that the integration build works as expected, tag the release: `git tag v4.3.0 && git push origin v4.3.0` (CI builds, tests & pushes to the production container registry with a v4.3.0 image tag)
* If we need to bugfix, we go back to the v4.3.0 tag, and create a branch off of it. (`git checkout -b main_v4.3.0 v4.3.0` - we could also create the branch at release time if we would rather do that) We can then bring changes from development, to main and up to the release branch. (Or however we want to get changes into the new release - we could just continue committing to `main` and tagging off of it if we haven't had another release yet) Once we're ready to test we'd tag a `v4.3.1-rc1` integration tag which would kick off an integration CI build, and then a `v4.3.1` tag when we think we're ready for CI to create the production images.

Does that sound alright?

**Pull request merged**
