### PR TITLE
Cb ceiling middleware die off

### PR DESCRIPTION
**Pull request by gopa-noaa**
Merge middleware based DieOff and Time Series station plot CTC generator code to development for app cb_ceiling.

### CODE REVIEW

**Comment by gopa-noaa** [comment]
removed code duplication per code review with Molly, Randy

**Comment by gopa-noaa** [comment]
Please ignore MATScommon/meteor_packages/mats-common/imports/startup/server/matsMiddle_ts_dieoff.js in your review, that is an unfinished and unused implementation that will be dealt with in another PR.

**Review by randytpierce — APPROVED** [review]
I assume any tests are still working. I don't see anything wrong here. Approve.

**Comment by mollybsmith-noaa** [comment]
Approved and looks good, but hold off merging until I can merge the existing development into main?

**Review by mollybsmith-noaa — APPROVED** [review]

**Pull request merged**
