### PR TITLE
Update the base image

### LINKED ISSUE #613: Use Trivy to identify and resolve container vulnerabilities
Use the standalone [Trivy](https://github.com/aquasecurity/trivy) container scanning tool to identify vulnerabilities in the MATS & METexpress container images. [Trivy's docs can be found here](https://aquasecurity.github.io/trivy/v0.18.3/).

### PR DESCRIPTION
**Pull request by ian-noaa**
Update base image to a more recent version of node and alpine

While we're at it - simplify the Dockerfile and improve our build times.

Closes #613

### CODE REVIEW

**Comment by ian-noaa** [comment]
Building an image locally is giving me:

```console
$ trivy image <local-aircraft-container>
2021-08-13T15:24:58.255-0500	INFO	Detected OS: alpine
2021-08-13T15:24:58.255-0500	INFO	Detecting Alpine vulnerabilities...
2021-08-13T15:24:58.260-0500	INFO	Number of language-specific files: 0

dev-aircraft (alpine 3.14.1)
============================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by ian-noaa** [comment]
Added changes to simplify Dockerfile, to remove duplicate statements, and (particularly in 57d16d5) to reduce image size by ~60 MB and reduce build time from 680 to 170 seconds. (11 minutes to <3 minutes)

**Comment by ian-noaa** [comment]
@randytpierce - would you be able to give this a review? I've made some changes to the Dockerfile that take care of our security issues and that should reduce our build time substantially. However, I did remove some components and want to make sure they don't raise any red flags with you since you're much more familiar with why they were added. At a high level, I've:

* Upgraded the base image to node14.17 and alpine 3.14. This took care of the vulnerabilities Trivy was finding with the image OS.
* Removed some unused variables (`METEOR_NODE_VERSION`, `METEORD_DIR` - I wasn't seeing them used in the codebase and they weren't listed in the [Meteor docs](https://docs.meteor.com/environment-variables.html)) and de-duplicated the `APPNAME` variable.
* Switched to apk packages for numpy & pip to drop container image build times ~400%. (11 min -> under 3 min)
* Bugfixed the spelling of the `newCodeCommit` variable and removed some duplicate `rm` lines
* Removed the line that installed the `n` package manager since it wasn't being used anywhere.
* Removed the line that ran `npm cache clean -f`. This was happening in a clean container and wasn't doing anything.

I tested the aircraft app in the resulting container and it appeared to work fine. Let me know if you have any concerns over what's been removed.

**Review by randytpierce — APPROVED** [review]
This all looks great, if it actually produces a good image. The py3-numpy is a great introduction and I can see how it would make the build much faster. 

I still do not quite understand how we do not need the mariadb-dev requirement.

We should build this way and test it on dev.

**Comment by ian-noaa** [comment]
Sounds good! For the record - we're testing on a dev server with:

```console
$ time scripts/common/mats_build_deploy_apps_parallel.sh -e dev -i -a -b 613-resolve-vulnerabities | tee /builds/ian.out
```

**Comment by ian-noaa** [comment]
Just an FYI - I'm going to split this PR into two since I started doing CI work in here. The work updating the container image will be captured in #635  while the CI work will be captured in #634. 

I'll close this PR when those are ready to go.

**Comment by ian-noaa** [comment]
Closing in favor of #635

**Pull request closed without merging**
