### PR TITLE
Apply linting to cb ceiling

### LINKED ISSUE #896: Apply Linting to cb-ceiling
PR #893 didn't apply our linters to the `apps/cb-ceiling` app in order to avoid some messy merge conflicts with PR #851. Once that PR is merged, we can apply the linters to `apps/cb-ceiling` and enable checks for `cb-ceiling` in CI. 

We will want to make sure that `*.sql` files aren't edited by Prettier.

We will also want to make sure that a `.git-blame-ignore-rev` file has been added to the repo to ignore the commits where we implemented the linters. Currently a636feddfb5ec93aabe6d84c7e50bbf96879004c, 83f8513d277205ba316499cfd6f9f2d23b483ad8, and whichever commit we do to apply them to cb-ceiling.

### PR DESCRIPTION
**Pull request by ian-noaa**
Finish the work started in #884 to transition the MATS apps to be formatted by Prettier and linted by Eslint. 

Closes #896

### CODE REVIEW

**Review by mollybsmith-noaa — APPROVED** [review]
This all looks reasonable. Can you verify that you are able to produce at least one of each type of plot before the merge, just to make sure nothing got messed up? This is our first linted couchbase app so it's probably good to double-check.

**Comment by ian-noaa** [comment]
Certainly. I'm not sure if the graphs below are valid/sensical from a meteorological standpoint. However, graphs were produced!

Timeseries:
image

Dieoff:
image

Threshold:
image

ValidTime:
image

DailyModelCycle:
image

PerformanceDiagram:
image

Map:
image

Histogram:
image

Contour:
image

ContourDiff:
image

**Comment by mollybsmith-noaa** [comment]
They look plausible. Go ahead and merge it once Gopa approves!

Molly

**Review by gopa-noaa — APPROVED** [review]
Looks good!

**Pull request merged**
