### PR TITLE
629 upgrade bootstrap 5

### PR DESCRIPTION
**Pull request by ian-noaa**
Initial attempt at migrating from bootstrap 4 to 5.  This is just a draft and we can delete it if there's a better direction to go in.

This branch will need the 629-upgrade-bootstrap-5 MATScommon branch checked out as well. In MATS - I've upgraded bootstrap to v5 everywhere I could find it and removed the duplicate bootstrap 3 dependency from the atmosphere package list. I'm not sure if this was wise. Either way, it resulted in a very broken MATS UI.

### CODE REVIEW

**Comment by mollybsmith-noaa** [comment]
As a heads up, you're also going to want to create that branch in METexpress, if you want to avoid having trouble with the build.

**Comment by ian-noaa** [comment]
Thanks Molly! You were a few minutes ahead of me. I've pushed my MATScommon changes here: https://github.com/dtcenter/MATScommon/pull/4

This is all just a shot in the dark at seeing if I could get something working. (Spoiler - the UI's pretty broken with this change) I'd definitely appreciate your thoughts on what I pushed.

**Comment by mollybsmith-noaa** [comment]
I'll take a look after this meeting! Thanks, Ian!

**Comment by mollybsmith-noaa** [comment]
These changes look like a good start! If Hera isn't back up after our next meeting (it probably won't be), I'll checkout some local branches and see if I see anything causing the GUI not to work properly.

It looks like the individual apps don't have any access to bootstrap or jQuery anymore, and they might not need it, but have you checked that yet?

**Comment by mollybsmith-noaa** [comment]
Would you mind creating this branch in METexpress too, so that I know I'm testing the correct code? (Also, those apps will have the same meteor packages that need updating).

**Comment by ian-noaa** [comment]
Can do. Do you just need the branch name to exist? I should mention - I only upgraded MATScommon and the aircraft app in MATS to keep things as simple as possible for now.

**Comment by mollybsmith-noaa** [comment]
Just existing is fine! I just end up getting really confused if half of my project is on development and half is on a feature branch. Plus it’s really easy to accidentally push unfinished code to origin/development that way, I’ve done that more times than I want to admit :)

**Pull request closed without merging**
