### PR TITLE
Feature met mode

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
The MATS component of the pull request for my MET MODE app. Nothing in this one is very important, it's mostly upgrading the apps to Meteor 2.6.1 and fixing a typo bug in upperair.

### CODE REVIEW

**Review by ian-noaa — CHANGES_REQUESTED** [review]
If we're upgrading Meteor, we should make sure the Dockerfile is updated to match the version we're using. The line to upgrade is here: https://github.com/NOAA-GSL/MATS/blob/dc6da652b414bfb44f40d8f78b9124abf7270ec7/Dockerfile#L2

And the tags for the base image can be found here: https://hub.docker.com/r/geoffreybooth/meteor-base/tags. Looks like we'll want to use `geoffreybooth/meteor-base:2.6.1`

**Comment by mollybsmith-noaa** [comment]
Thanks for spotting that! I'll make the changes.

**Comment by mollybsmith-noaa** [comment]
Changes have been made, and I finally got the subrepo pointers to actually be what they're supposed to.

**Review by ian-noaa — APPROVED** [review]
Thanks, Molly! Pending a successful build, looks great to me!

**Pull request merged**
