### PR TITLE
Feature bug fixes sept2021

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
The MATS repo pull request for my September bug fixes and feature additions. I'm sorry about the sheer number of things included in a single pull request, as I ended up doing more than I had anticipated. I will try to plan this better next time.

I have NOT been able to run the automated browser tests on these modifications, as the CSS paths are different on localhost (I think there is an extra top-level <div> or something throwing things off), but I have done enough manual testing that I am confident merging these changes to our development branch, where I will then run the tests and patch any bugs as necessary. They should be minor, though, everything seems to work pretty well.

Changes include (over all three repos):
* Improved METexpress app selector defaults, mainly for AWS.
* Improved METexpress automated browser tests for AWS.
* Updated METexpress metadata scripts to remove metadata for databases that no longer exist.
* Matching timeseries with disparate curve averages is no longer banned.
* Improved the handling of curve defaults when the plot type is changed.
* Possibly fixed the double value string bug that can happen after a metadata update.
* Integrated plotly's curve show/hide mechanisms with our own.
* Added button to move all curves to one y-axis (or x-axis for profiles).

### CODE REVIEW

**Review by randytpierce — APPROVED** [review]

**Review by ian-noaa — APPROVED** [review]
There's a lot here so to my knowledge, it looks good.

Two thoughts:
- would it be possible to [link the issues related to this PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) so that it's easy to figure out what issues lead to these code changes?
- would it be a good idea to open an issue to fix the test suite so we don't forget it's broken?

**Comment by mollybsmith-noaa** [comment]
Would it be acceptable to link issues to a milestone, as discussed earlier? A lot of issues span variable combinations of MATS, MATScommon, and METexpress. Thanks for reviewing, BTW!

**Comment by ian-noaa** [comment]
Linking issues to a milestone (release) serves a different purpose than linking them to a PR (code changes). So I'd recommend making sure issues link to their related PR (so we can see what changes they lead to in the code) and then depending on how we want to manage releases we could assign issues to milestones/project boards. (We could also have a project board per release)

The reason it's useful to have the issue linked to the code change is so it's easy to reference information and conversations in the issue when reviewing the code. It's also helpful later when you're looking at things from a historical perspective. (Or if we need to revert a change so we know what we're undoing)

I usually add `Closes #<issue number>` at the end of my PR description or in one of my commits so GitHub/Lab automatically set up the linking - otherwise, it can be done from the UI as well. I _think_ we can also link issues & PR's cross-repos.

**Comment by mollybsmith-noaa** [comment]
Okay, but you are going to have probably 2/3 of the issues being in MATS, none being in MATScommon (issues tracked in both MATS and METexpress may result in MATScommon code changes, but nothing is tracked in MATScommon itself. At the start we often don't know if a bug is going to be in the common code or not, so we err on the side of filing the issue in the tool suites likely to be affected), and 1/3 in METexpress. Does that work for you?

**Comment by ian-noaa** [comment]
I think so, it's a reflection of how the project works. The important thing is to be able to figure out why we're making the change - regardless of the project the idea originated/is tracked in.

**Pull request merged**
