### PR TITLE
Scorecard display

### PR DESCRIPTION
**Pull request by ian-noaa**
Draft PR with some scorecard improvements

### CODE REVIEW

**Comment by ian-noaa** [comment]
@randytpierce - it looks like the merge conflicts on this PR in MATScommon are preventing CI from running. We'll want to resolve those before merging to `development`.

**Comment by mollybsmith-noaa** [comment]
@randytpierce @ian-noaa Instructions for fixing that conflict (in the subrepo pointer) are described in step 12 in this google doc: https://docs.google.com/document/d/1hhIY7kEMdxUdELdV4ynyQ_pdZl9gYAjRAuiu15FCEds/edit

**Comment by randytpierce** [comment]
I have pushed some new changes and I think this is ready to be reviewed and merged.

**Review by mollybsmith-noaa — APPROVED** [review]
I approve this PR pending the automated tests passing, and pending Gopa's approval of the cb_utilities.js changes.

**Comment by gopa-noaa** [comment]
@randytpierce 
On MATScommon/meteor_packages/mats-common/imports/startup/server/cb_utilities.js

I see you have:
timeouts: {
            kvTimeout: 3600000, // this will kill queries after an hour
          },
The development branch was updated as below:

const cluster = await couchbase.connect(this.host, {
                    username: this.user,
                    password: this.pwd,
                    timeouts: {
                        kvTimeout: 3600000, // this will kill queries after an hour
                        queryTimeout: 3600000
                    }
                });
Can you pull the latest from development ?

**Comment by randytpierce** [comment]
added new package-lock.json files

**Pull request merged**
