### PR TITLE
Create a home app

### PR DESCRIPTION
**Pull request by ian-noaa**
Create a home app using Go & Gin with templated HTML and minimal JS. 

This PR mimics the style of the original home app as much as possible. However, it updates the UI to use Bootstrap 5. I did add a favicon & a page title as well to make the MATS landing page look more official.

I've done a few additional things as they were easy to do now that we have a Go server:
- I added a `/health` endpoint to the application so that we can use [automated health checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) in Kubernetes. 
- I added some basic Prometheus metrics so we can tell if the app is up and if it's taking longer than expected to respond to users. In the future we may be able to instrument the app links so we can tell how often certain apps are used. Otherwise, we could implement something like Google Analytics to get that info.
- Added containerization and CI around the project so we can deploy it.

This is intended to slot into our current docker-compose stacks and replace `matsapps/production:mats-http` which is this Go file server: https://github.com/halverneus/static-file-server. Obviously, we could also deploy this in Kubernetes.

This PR is stacked on top of #1031 and under #1037.

### CODE REVIEW

**Comment by ian-noaa** [comment]
@mollybsmith-noaa & @randytpierce - If you want to check it out, I've deployed a preview of the app at: https://apps-dev2.gsd.esrl.noaa.gov/mats-dev/. Note that the MET apps and the ensemble app aren't expected to work yet as they aren't deployed in the cluster. The URL should be correctly formed though.

Some questions:
- Is a Go app acceptable here? How do we feel about supporting it? It's a "new" language for MATS but the app itself is relatively simple and it uses the same technologies as vxDataProcessor. Go allows for quick build times and some useful instrumentation via Prometheus. I think not needing a Mongo instance is an advantage given what the home page needs to do. The biggest downside I see of not going with Meteor is that we can't reuse the header & footer from mats-common. They seem easy to replicate though and pulling in mats-common would bring a lot of dependencies that we won't use. (E.g. Couchbase)
- The styling has been slightly modified from MATS - most of this is due to the move to bootstrap 5. Are the changes acceptable?
- Does this belong in the MATS repo? A standalone repo would be easier to reason about from a CI perspective. However, having the code in one place is advantageous for project management. 

And one known deficiency - I haven't implemented testing yet.

**Comment by mollybsmith-noaa** [comment]
From a design standpoint, can we a) have a 1em margin at the top of the page, and b) not bold that button font? It's a bit heavy as is.
Screenshot 2023-08-16 at 1 32 10 PM

**Review by mollybsmith-noaa — CHANGES_REQUESTED** [review]
The code all looks good, but I requested a couple of design changes in a comment. Thanks for working on this!

**Review by randytpierce — APPROVED** [review]
Really nice. I really like how GO handles the templates. I think the code is fine and I'll defer look and feel issues to Molly. I would like to see the buttons disable if the app cannot retrieve the version from the picker route of each app. It might also be nice to present the version in a tooltip when one hovers over the app. Makes it easy to see what the build of each app actually is. Those can be future enhancements.

**Comment by mollybsmith-noaa** [comment]
I dunno, I’ve really gone off of the tooltips since the scorecard app. They’re more persistent than they should be and they cover up whole buttons so those buttons can’t be clicked.

**Comment by ian-noaa** [comment]
Yeah, I've been pleasantly surprised with how templating works in Go. It's also been good practice for Helm Chart templating since that's Go templates combined with YAML. And I'll open some tickets for those other features!

Otherwise, does this seem okay to merge into MATS (once approved) or do we want it in its own repo?

@mollybsmith-noaa - I went ahead and updated the container image on https://apps-dev2.gsd.esrl.noaa.gov/mats-dev/ with the latest from this branch. (screenshot below) I _should_ have updated things based on all the feedback you gave me. However, I got fancy and added some toggles to show/hide the app selectors based on the "Verification Source". Let me know what you think!

I also switched us to use more native Bootstrap elements and moved the styling into a CSS file. 

image

**Comment by ian-noaa** [comment]
@mollybsmith-noaa - The home app should now collapse the group headers as well when there aren't any apps to display. You can find a preview at https://apps-dev2.gsd.esrl.noaa.gov/mats-dev. (Or run it locally) Let me know what you think! You'll need to approve before I can merge.

**Review by mollybsmith-noaa — APPROVED** [review]
I like it! Out of curiosity, is there a METexpress version we could use for AWS? If not we can keep using the static template for now.

**Pull request merged**
