### PR TITLE
Update meteor and npm packages

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
This PR updates meteor to 2.15 and also updates other meteor and npm packages.

### CODE REVIEW

**Comment by JeffHamiltonNOAA** [comment]
Will not having a docker image available with this version of meteor cause problems during deployment to mats-docker? Or maybe I’m not understanding correctly?

**Comment by mollybsmith-noaa** [comment]
Ideally you want meteor-base to match the version of meteor you’re using,
but this is far from the first time that they’ve been slow to release one,
and the apps have always worked fine before. This would be the sixth or
seventh time we had a mismatch, and like I said it’s always been fine, but
if you think we should wait then we can.

**Comment by mollybsmith-noaa** [comment]
At the very least it will be obvious if it *doesn’t* work, as none of our
apps will start.

**Comment by JeffHamiltonNOAA** [comment]
Fair enough. I figured that this isn’t something completely new that we encountered, so we’ll see how it goes. Thanks again!

**Pull request merged**
