### PR TITLE
719 fix deploy action failure

### PR DESCRIPTION
**Pull request by ian-noaa**
Whitespace isn't valid in a `${ENV}` block. Also, remove the leading `refs/tags/` as we don't want that in our image tags.

This was tested in a sandbox repo here: https://github.com/ian-noaa/github-actions-playground/runs/5879432800?check_suite_focus=true with the following GitHub Actions file: https://github.com/ian-noaa/github-actions-playground/blob/dc29529916f73937d33e562097801f79eb7522ab/.github/workflows/test-syntax.yml

The results from the test show that the whitespace was the issue and that using syntax like: `${GITHUB_REF:/refs/tags/}` is valid and will trim the extra parts of the ref we don't want in our image tags.

### CODE REVIEW

**Comment by ian-noaa** [comment]
@mollybsmith-noaa & @randytpierce - could you review this? I spent some time late last night looking into this in a sandbox repo and discovered the whitespace in `${ GITHUB_REF }` was the issue. I've updated those sections of the action and have also added some bash string manipulation to trim some unwanted parts of the GITHUB_REF result.

**Review by mollybsmith-noaa — APPROVED** [review]
It looks like the release note changes are getting pulled in? I guess go for it, I can fix that later if you let me do the re-tagging.

**Comment by ian-noaa** [comment]
Yeah. It looks like this updates `development` to the latest version of the release notes in MATScommon. Looking at this PR branch - it appears that GitHub created it off of `main` instead of `development` so I could reopen the PR with the branch based off of `development` instead.

**Comment by mollybsmith-noaa** [comment]
That would have the same problem, though. Just merge this one and I’ll make
sure everything is correct before I do the tags.

**Comment by ian-noaa** [comment]
Closing in favor of #721

**Pull request closed without merging**
