### PR TITLE
Cb ceiling middle tier plots

### PR DESCRIPTION
**Pull request by gopa-noaa**
Merge cb_ceiling_middle_tier_plots branch with development.  
Issues resolved:
cb-ceiling - merge middleware code for multiple plot types #1036
cb-ceiling - too high skill (CSI) score for multiple region plots #1044

### CODE REVIEW

**Review by mollybsmith-noaa — CHANGES_REQUESTED** [review]
This looks good. The only change that I think we need is that some files still have `import {memoryUsage} from node:process`, which doesn't work in our containers for whatever reason. Can you remove this and make sure it's not referenced anywhere?

**Comment by gopa-noaa** [comment]
@mollybsmith-noaa removed memoryUsage imports and pushed

**Review by mollybsmith-noaa — APPROVED** [review]
This looks good. The build checks failed, which sometimes just happens because github drops the ball, but can you run cb-ceiling and at least one mysql app locally from your feature branch to make sure everything is working before you merge?

**Comment by mollybsmith-noaa** [comment]
The build errors in this PR are because a non-existent METexpress tag was checked in. I will fix it.

**Comment by gopa-noaa** [comment]
MySQL app works fine, merged to development.

**Pull request closed without merging**
